/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Forest Realm - QUESTFOLIO Design Tokens
        "on-tertiary-fixed": "#00210c",
        "tertiary-fixed-dim": "#4de082",
        "on-error": "#ffffff",
        "on-primary-container": "#00422b",
        "primary-container": "#10b981",
        "surface": "#eaffe8",
        "on-primary": "#ffffff",
        "surface-variant": "#cbebcb",
        "inverse-primary": "#4edea3",
        "outline-variant": "#bbcabf",
        "on-primary-fixed": "#002113",
        "surface-container-highest": "#cbebcb",
        "surface-bright": "#eaffe8",
        "error-container": "#ffdad6",
        "surface-dim": "#c3e2c3",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#005227",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#06200d",
        "on-background": "#06200d",
        "secondary-fixed-dim": "#aecfa9",
        "on-error-container": "#93000a",
        "tertiary": "#006d36",
        "secondary": "#486646",
        "surface-tint": "#006c49",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#d9f9d9",
        "surface-container": "#d6f6d7",
        "surface-container-high": "#d1f0d1",
        "secondary-container": "#c9ecc4",
        "primary": "#006c49",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4d6c4c",
        "on-surface-variant": "#3c4a42",
        "outline": "#6c7a71",
        "primary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#005236",
        "primary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#304e30",
        "on-secondary-fixed": "#042108",
        "secondary-fixed": "#c9ecc4",
        "background": "#eaffe8",
        "inverse-surface": "#1c3621",
        "tertiary-container": "#11bb62",
        "tertiary-fixed": "#6dfe9c",
        "surface-container-low": "#dcfcdc",
        "on-tertiary-container": "#00431e",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "step-lg": "24px",
        "step-3xl": "64px",
        "container-max": "1200px",
        "step-xl": "32px",
        "step-2xl": "48px",
        "gutter-desktop": "24px",
        "step-sm": "8px",
        "step-xs": "4px",
        "gutter-mobile": "16px",
        "pixel-unit": "2px",
        "step-md": "16px",
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "display-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Space Grotesk", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        // Legacy aliases kept for compatibility
        "section-title": ["Space Grotesk", "sans-serif"],
        "headline-display": ["Space Grotesk", "sans-serif"],
        "body-base": ["Space Grotesk", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "30px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}