/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdea9",
        "surface-dim": "#1c110b",
        "surface-tint": "#f9bc47",
        "secondary": "#99d77a",
        "surface-container": "#2a1d16",
        "tertiary-fixed-dim": "#ffb1c1",
        "on-primary": "#422c00",
        "inverse-on-surface": "#3c2d26",
        "on-tertiary-container": "#8d2c48",
        "surface-container-low": "#251913",
        "on-primary-fixed": "#271900",
        "secondary-container": "#1b5201",
        "surface-container-high": "#352720",
        "tertiary-fixed": "#ffd9df",
        "primary-container": "#f4b843",
        "secondary-fixed": "#b4f493",
        "on-error": "#690005",
        "surface-variant": "#40322b",
        "tertiary-container": "#ffabbc",
        "on-surface-variant": "#d4c4af",
        "tertiary": "#ffd3da",
        "error-container": "#93000a",
        "surface-bright": "#45362f",
        "surface-container-highest": "#40322b",
        "inverse-primary": "#7d5800",
        "on-secondary-container": "#88c56a",
        "on-tertiary-fixed-variant": "#812340",
        "surface": "#1c110b",
        "error": "#ffb4ab",
        "on-secondary": "#103900",
        "outline": "#9c8f7b",
        "inverse-surface": "#f6ded3",
        "on-secondary-fixed-variant": "#1b5201",
        "on-background": "#f6ded3",
        "surface-container-lowest": "#160c06",
        "on-primary-container": "#6a4a00",
        "secondary-fixed-dim": "#99d77a",
        "on-primary-fixed-variant": "#5e4100",
        "background": "#1c110b",
        "on-secondary-fixed": "#062100",
        "on-tertiary": "#63092a",
        "on-surface": "#f6ded3",
        "primary-fixed-dim": "#f9bc47",
        "on-tertiary-fixed": "#3f0017",
        "outline-variant": "#504535",
        "primary": "#ffd999",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#3A2408"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem",
        "gutter": "1.5rem",
        "space-lg": "2rem",
        "margin": "2.5rem",
        "space-xl": "3rem",
        "step-lg": "24px",
        "step-3xl": "64px",
        "container-max": "1200px",
        "step-xl": "32px",
        "step-2xl": "48px",
        "gutter-desktop": "24px",
        "step-sm": "8px",
        "step-xs": "4px",
        "gutter-mobile": "16px",
        "pixel-unit": "2px",
        "step-md": "16px"
      },
      fontFamily: {
        "headline-lg": ["Space Mono", "monospace"],
        "label-sm": ["Space Mono", "monospace"],
        "body-lg": ["Space Mono", "monospace"],
        "label-lg": ["Space Mono", "monospace"],
        "body-sm": ["Space Mono", "monospace"],
        "headline-md": ["Space Mono", "monospace"],
        "body-md": ["Space Mono", "monospace"],
        "headline-xl": ["Space Mono", "monospace"],
        "label-md": ["Space Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-mobile": ["Space Grotesk", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "section-title": ["Space Grotesk", "sans-serif"],
        "headline-display": ["Space Grotesk", "sans-serif"],
        "body-base": ["Space Grotesk", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "0em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-lg": ["16px", { "lineHeight": "22px", "letterSpacing": "0.06em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-mobile": ["36px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "26px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
